[build]
  command = "cd demo && yarn && yarn build"
  publish = "demo/.next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "."

  [plugins.inputs]
  cloudName = "colbycloud"